name: smart_restaurant_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_web_plugins:
    sdk: flutter
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  simple_shadow: ^0.3.0
  blur: ^3.1.0
  dio: ^4.0.6
  expandable_page_view: ^1.0.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  form_validator: ^1.0.2
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  carousel_slider: ^4.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600




